### ISSUE TITLE
bug when closed with the X in the bottom right

### ISSUE THREAD

**Issue by simone-viozzi** [brendena/MathEquations-Extension#1]
hi 
when this extension is closed by pressing the big X in the bottom right of the screen it doesn't reopen when the extension icon in the plug-in bar is pressed.
thanks

**Comment by brendena** [comment]
This bug was fixed with version 1.4

The problem was that i didn't have a way of reloading the extension.  In version 1.3 the popup UI managed all the downloading in the extension.  Since the popup doesn't directly have access to the main pages down.  I didn't know when the user removed the extension.

Now the popup send a message to the content script telling it load the extension.  The content script can easily check and manage adding and remove the extension from messages from the browser action or by user action in the UI of the extension.

Thanks for the bug reports.
