### ISSUE TITLE
resizing equation

### ISSUE THREAD

**Issue by simone-viozzi** [brendena/MathEquations-Extension#2]
when i write a long formula in latex 
es: 
" E[\hat{\sigma^2}]=E\left[ \frac{\sum_{i=1}^{n}(x_i-\bar{x_n})^2}{n} \right]=\frac1nE\left[ \displaystyle\sum_{i=1}^{n}(x_i-\bar{x_n})^2 \right]=\frac1nE\left[ \displaystyle\sum_{i=1}^{n}(x_i^2-2\bar{x_n}x_i+x_n^2) \right]=\\
=\frac1n " 
the image produced is:
![png base645659b969aca9c019](https://user-images.githubusercontent.com/19674168/33018114-5d99435a-cdf5-11e7-8bff-23c3b17ff73c.png)
instead a single row for the first four equalities.
thanks

**Comment by brendena** [comment]
It should be fixed now.   

In the background there a canvas element that i have to match the "math equations svg" width to height ratio to make sure it look proper.  Else it will overlaps like in the examples above.  

The problem was i was applying the height and width property to the style of the canvas and not to the actually canvas.  So the pixel ratio of the canvas never changed just the appearance of it did.
